[build]
builder = "dockerfile"

[deploy]
startCommand = "python manage.py migrate && gunicorn --bind 0.0.0.0:$PORT --timeout 120 --workers 2 config.wsgi:application"
healthcheckPath = "/health/"
restartPolicyType = "on_failure"

[[services]]
name = "chatbox-ai"
