# Generated by Django 6.0.3 on 2026-04-16 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0003_alter_chatsession_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileattachment',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
